### PR TITLE
Job Tracking and parrellelDispatch

### PR DESCRIPTION
**Pull request by Orrison**
The meat and potatoes. How it works is described in the `README.md`

### CODE REVIEW

**Review by skylerkatz — COMMENTED** [review]
This looks really cool.

My two notes of feedback are
 -`$completionJob` and `$completionJobArgs`. Is there a reason why you don't pass a fully formed `new CompletionJob($arg1, $arg2)` as a third param? My understanding of the cache is that you can cache a full class. The below seems to work in Tinker
```php
class Interesting {
  public $one;
  public $two;
  public $user;
  public function __construct(string $one, array $two)
  {
    $this->one = $one;
    $this->two = $two;
    $this->user = User::make();
  }
  public function doSomething($thing)
  {
    return $thing;
  }
}

$interesting = new Interesting('hello', ['array', 'values']);

Cache::forever('key', $interesting);


$cached = cache()->get('key');

echo $cached->doSomething('works');
```

My other feedback would be around the `$uniqueGoalKey`. Why is this key needed at all? Couldn't you generate that within the trait/function all on its own without the need to have the user pass in a random key?

**Comment by Orrison** [comment]
> This looks really cool.
> 
> My two notes of feedback are
> -`$completionJob` and `$completionJobArgs`. Is there a reason why you don't pass a fully formed `new CompletionJob($arg1, $arg2)` as a third param? My understanding of the cache is that you can cache a full class. The below seems to work in Tinker
> 
> ```
> class Interesting {
>   public $one;
>   public $two;
>   public $user;
>   public function __construct(string $one, array $two)
>   {
>     $this->one = $one;
>     $this->two = $two;
>     $this->user = User::make();
>   }
>   public function doSomething($thing)
>   {
>     return $thing;
>   }
> }
> 
> $interesting = new Interesting('hello', ['array', 'values']);
> 
> Cache::forever('key', $interesting);
> 
> 
> $cached = cache()->get('key');
> 
> echo $cached->doSomething('works');
> ```
> 
> My other feedback would be around the `$uniqueGoalKey`. Why is this key needed at all? Couldn't you generate that within the trait/function all on its own without the need to have the user pass in a random key?

You know, I tried to pass the whole class and for some reason it did not work. But I will try it again. Maybe I just didn't do it right the first time I tested it. Honestly I would prefer just to do the class.

For `$uniqueGoalKey`, that is true. I could just generate it when you run the function. My only thought was this gave the user a way to give it a name that you they could check on later on the cache. But then again it is tied to the job so if you wanted info on whether or not something completed and what it was the failed jobs table is probably fine..

**Comment by skylerkatz** [comment]
It seems like you could potentially add a table/model that tracks this info as part of the package, or a console command that pulls out the info and displays it as a table.

It feels _clunky_ to require it if there is no built in experience to do anything with it.
You could always put it as an optional last param.

**Comment by Orrison** [comment]
That makes a lot of sense. I have gone ahead and removed adding that ID manually for now. Maybe I will add in something later to allow for optionally setting it then some tracking.

Also adjust documentation.

**Comment by Orrison** [comment]
@skylerkatz wondering if you had any additional comments on this. I made the changes based on your suggestions

**Pull request merged**
